FROM osrg/ryu:latest
RUN apt-get -y update
RUN apt-get install -y nano
RUN apt-get install -y iputils-ping
RUN apt-get install -y tcpdump
RUN apt-get install -y iproute2
RUN apt-get install -y iptables
RUN apt-get install -y net-tools
RUN apt-get install -y python3
RUN apt-get install -y wget
######## sudo docker build -f Dockerfile.Ubuntu -t host:latest .  #########
